name: Test

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Install Fluter
      uses: subosito/flutter-action@v1.4.0
      with:
        channel: 'stable' # or: 'beta' or 'dev'
    - name: Install app dependencies
      run: flutter pub get
    - name: Test app
      run: flutter test
