---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cirrusci/flutter
    tag: 1.22.2

inputs:
- name: flutter_unit_widget_tests

caches:
- path: flutterpath/

params:
  COVERALLS_TOKEN:
  GIT_BRANCH: master

run:
 path: flutter
 args: ["doctor"]
